/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.myssyt.bibtex;

/**
 *
 * @author jphkylli
 */
public class ArticlePanel extends javax.swing.JPanel {
    // todo
    /*
        An article from a journal or magazine. 
            Required fields: 
                author, title, journal, year. 
            Optional fields: 
                volume, number, pages, month, note.
    */

    /**
     * Creates new form BookPanel
     */
    public ArticlePanel() {
        initComponents();
    }
    
    public void clearTextFields() {
        
        optionalFieldsScrollPane.getVerticalScrollBar().setValue(optionalFieldsScrollPane.getVerticalScrollBar().getMinimum());
        
        getTfAuthor().setText("");
        getTfBibtexkey().setText("");
        getTfBooktitle().setText("");
        getTfMonth().setText("");
        getTfNote().setText("");
        getTfNumber().setText("");
        getTfPages().setText("");
        getTfTitle().setText("");
        getTfVolume().setText("");
        getTfYear().setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lAuthor = new javax.swing.JLabel();
        tfAuthor = new javax.swing.JTextField();
        tfTitle = new javax.swing.JTextField();
        lTitle = new javax.swing.JLabel();
        tfBooktitle = new javax.swing.JTextField();
        lBooktitle = new javax.swing.JLabel();
        tfYear = new javax.swing.JTextField();
        lYear = new javax.swing.JLabel();
        tfBibtexkey = new javax.swing.JTextField();
        lBibtexkey = new javax.swing.JLabel();
        optionalFieldsScrollPane = new javax.swing.JScrollPane();
        optionalFieldsPanel = new javax.swing.JPanel();
        tfVolume = new javax.swing.JTextField();
        tfMonth = new javax.swing.JTextField();
        tfNumber = new javax.swing.JTextField();
        tfPages = new javax.swing.JTextField();
        lVolume = new javax.swing.JLabel();
        lNumber = new javax.swing.JLabel();
        lSeries = new javax.swing.JLabel();
        lAddress = new javax.swing.JLabel();
        tfNote = new javax.swing.JTextField();
        lNote = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Article"));
        setPreferredSize(new java.awt.Dimension(100, 100));

        lAuthor.setText("Author");

        lTitle.setText("Title");

        lBooktitle.setText("Journal");

        lYear.setText("Year");

        lBibtexkey.setText("Bibtexkey");

        optionalFieldsScrollPane.setBorder(javax.swing.BorderFactory.createTitledBorder("Optional Fields"));
        optionalFieldsScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        lVolume.setText("Volume");

        lNumber.setText("Number");

        lSeries.setText("Pages");

        lAddress.setText("Month");

        lNote.setText("Note");

        javax.swing.GroupLayout optionalFieldsPanelLayout = new javax.swing.GroupLayout(optionalFieldsPanel);
        optionalFieldsPanel.setLayout(optionalFieldsPanelLayout);
        optionalFieldsPanelLayout.setHorizontalGroup(
            optionalFieldsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(optionalFieldsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(optionalFieldsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(optionalFieldsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(optionalFieldsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lVolume)
                            .addComponent(lNumber, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addComponent(lSeries))
                    .addComponent(lNote, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lAddress, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(optionalFieldsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfNote)
                    .addComponent(tfMonth)
                    .addComponent(tfVolume, javax.swing.GroupLayout.DEFAULT_SIZE, 706, Short.MAX_VALUE)
                    .addComponent(tfNumber)
                    .addComponent(tfPages))
                .addContainerGap())
        );
        optionalFieldsPanelLayout.setVerticalGroup(
            optionalFieldsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(optionalFieldsPanelLayout.createSequentialGroup()
                .addGroup(optionalFieldsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfVolume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lVolume))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(optionalFieldsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lNumber))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(optionalFieldsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfPages, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lSeries))
                .addGap(5, 5, 5)
                .addGroup(optionalFieldsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lAddress))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(optionalFieldsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lNote))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        optionalFieldsScrollPane.setViewportView(optionalFieldsPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(optionalFieldsScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 786, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lAuthor)
                            .addComponent(lTitle)
                            .addComponent(lBooktitle)
                            .addComponent(lYear)
                            .addComponent(lBibtexkey))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfAuthor)
                            .addComponent(tfTitle)
                            .addComponent(tfBooktitle)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfBibtexkey, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                                    .addComponent(tfYear))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lAuthor)
                    .addComponent(tfAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lTitle))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfBooktitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lBooktitle))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lYear))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfBibtexkey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lBibtexkey))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(optionalFieldsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(124, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lAddress;
    private javax.swing.JLabel lAuthor;
    private javax.swing.JLabel lBibtexkey;
    private javax.swing.JLabel lBooktitle;
    private javax.swing.JLabel lNote;
    private javax.swing.JLabel lNumber;
    private javax.swing.JLabel lSeries;
    private javax.swing.JLabel lTitle;
    private javax.swing.JLabel lVolume;
    private javax.swing.JLabel lYear;
    private javax.swing.JPanel optionalFieldsPanel;
    private javax.swing.JScrollPane optionalFieldsScrollPane;
    private javax.swing.JTextField tfAuthor;
    private javax.swing.JTextField tfBibtexkey;
    private javax.swing.JTextField tfBooktitle;
    private javax.swing.JTextField tfMonth;
    private javax.swing.JTextField tfNote;
    private javax.swing.JTextField tfNumber;
    private javax.swing.JTextField tfPages;
    private javax.swing.JTextField tfTitle;
    private javax.swing.JTextField tfVolume;
    private javax.swing.JTextField tfYear;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the tfAuthor
     */
    public javax.swing.JTextField getTfAuthor() {
        return tfAuthor;
    }

    /**
     * @param tfAuthor the tfAuthor to set
     */
    public void setTfAuthor(javax.swing.JTextField tfAuthor) {
        this.tfAuthor = tfAuthor;
    }

    /**
     * @return the tfBibtexkey
     */
    public javax.swing.JTextField getTfBibtexkey() {
        return tfBibtexkey;
    }

    /**
     * @param tfBibtexkey the tfBibtexkey to set
     */
    public void setTfBibtexkey(javax.swing.JTextField tfBibtexkey) {
        this.tfBibtexkey = tfBibtexkey;
    }

    /**
     * @return the tfBooktitle
     */
    public javax.swing.JTextField getTfBooktitle() {
        return tfBooktitle;
    }

    /**
     * @param tfBooktitle the tfBooktitle to set
     */
    public void setTfBooktitle(javax.swing.JTextField tfBooktitle) {
        this.tfBooktitle = tfBooktitle;
    }

    /**
     * @return the tfMonth
     */
    public javax.swing.JTextField getTfMonth() {
        return tfMonth;
    }

    /**
     * @param tfMonth the tfMonth to set
     */
    public void setTfMonth(javax.swing.JTextField tfMonth) {
        this.tfMonth = tfMonth;
    }

    /**
     * @return the tfNote
     */
    public javax.swing.JTextField getTfNote() {
        return tfNote;
    }

    /**
     * @param tfNote the tfNote to set
     */
    public void setTfNote(javax.swing.JTextField tfNote) {
        this.tfNote = tfNote;
    }

    /**
     * @return the tfNumber
     */
    public javax.swing.JTextField getTfNumber() {
        return tfNumber;
    }

    /**
     * @param tfNumber the tfNumber to set
     */
    public void setTfNumber(javax.swing.JTextField tfNumber) {
        this.tfNumber = tfNumber;
    }

    /**
     * @return the tfPages
     */
    public javax.swing.JTextField getTfPages() {
        return tfPages;
    }

    /**
     * @param tfPages the tfPages to set
     */
    public void setTfPages(javax.swing.JTextField tfPages) {
        this.tfPages = tfPages;
    }

    /**
     * @return the tfTitle
     */
    public javax.swing.JTextField getTfTitle() {
        return tfTitle;
    }

    /**
     * @param tfTitle the tfTitle to set
     */
    public void setTfTitle(javax.swing.JTextField tfTitle) {
        this.tfTitle = tfTitle;
    }

    /**
     * @return the tfVolume
     */
    public javax.swing.JTextField getTfVolume() {
        return tfVolume;
    }

    /**
     * @param tfVolume the tfVolume to set
     */
    public void setTfVolume(javax.swing.JTextField tfVolume) {
        this.tfVolume = tfVolume;
    }

    /**
     * @return the tfYear
     */
    public javax.swing.JTextField getTfYear() {
        return tfYear;
    }

    /**
     * @param tfYear the tfYear to set
     */
    public void setTfYear(javax.swing.JTextField tfYear) {
        this.tfYear = tfYear;
    }
}
