/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.myssyt.bibtex;

/**
 *
 * @author jphkylli
 */
public class BookPanel extends javax.swing.JPanel {
    /*
        A book with an explicit publisher. 
            Required fields: 
                author or editor, title, publisher, year. 
            Optional fields: 
                volume or number, series, address, edition, month, note.
    */

    /**
     * Creates new form BookPanel
     */
    public BookPanel() {
        initComponents();
    }
    
    public void clearTextFields() {
        
        optionalFieldsScrollPane.getVerticalScrollBar().setValue(optionalFieldsScrollPane.getVerticalScrollBar().getMinimum());
        
        getTfBibtexkey().setText("");
        
        getTfAuthor().setText("");
        getTfEditor().setText("");
        getTfTitle().setText("");
        getTfPublisher().setText("");
        getTfYear().setText("");
        
        getTfVolume().setText("");
        getTfNumber().setText("");    
        getTfSeries().setText("");
        getTfAddress().setText("");
        getTfEdition().setText("");
        getTfMonth().setText("");
        getTfNote().setText("");  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lTitle = new javax.swing.JLabel();
        tfTitle = new javax.swing.JTextField();
        tfPublisher = new javax.swing.JTextField();
        lPublisher = new javax.swing.JLabel();
        tfYear = new javax.swing.JTextField();
        lYear = new javax.swing.JLabel();
        tfAuthor = new javax.swing.JTextField();
        lAuthor = new javax.swing.JLabel();
        tfBibtexkey = new javax.swing.JTextField();
        lBibtexkey = new javax.swing.JLabel();
        optionalFieldsScrollPane = new javax.swing.JScrollPane();
        optionalFieldsPanel = new javax.swing.JPanel();
        tfVolume = new javax.swing.JTextField();
        tfAddress = new javax.swing.JTextField();
        tfNumber = new javax.swing.JTextField();
        tfSeries = new javax.swing.JTextField();
        tfEdition = new javax.swing.JTextField();
        tfMonth = new javax.swing.JTextField();
        tfNote = new javax.swing.JTextField();
        lVolume = new javax.swing.JLabel();
        lNumber = new javax.swing.JLabel();
        lSeries = new javax.swing.JLabel();
        lAddress = new javax.swing.JLabel();
        lEdition = new javax.swing.JLabel();
        lMonth = new javax.swing.JLabel();
        lNote = new javax.swing.JLabel();
        tfEditor = new javax.swing.JTextField();
        lEditor = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Book"));
        setPreferredSize(new java.awt.Dimension(100, 100));

        lTitle.setText("Title");

        lPublisher.setText("Publisher");

        lYear.setText("Year");

        lAuthor.setText("Author");

        lBibtexkey.setText("Bibtexkey");

        optionalFieldsScrollPane.setBorder(javax.swing.BorderFactory.createTitledBorder("Optional Fields"));
        optionalFieldsScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        lVolume.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lVolume.setText("Volume");
        lVolume.setPreferredSize(new java.awt.Dimension(90, 16));

        lNumber.setText("Number");

        lSeries.setText("Series");

        lAddress.setText("Address");

        lEdition.setText("Edition");

        lMonth.setText("Month");

        lNote.setText("Note");

        javax.swing.GroupLayout optionalFieldsPanelLayout = new javax.swing.GroupLayout(optionalFieldsPanel);
        optionalFieldsPanel.setLayout(optionalFieldsPanelLayout);
        optionalFieldsPanelLayout.setHorizontalGroup(
            optionalFieldsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, optionalFieldsPanelLayout.createSequentialGroup()
                .addGroup(optionalFieldsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lVolume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lNumber)
                    .addComponent(lSeries)
                    .addComponent(lAddress)
                    .addComponent(lEdition)
                    .addComponent(lMonth)
                    .addComponent(lNote))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(optionalFieldsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tfVolume, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 621, Short.MAX_VALUE)
                    .addComponent(tfAddress)
                    .addComponent(tfSeries, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfEdition, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfMonth, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfNote)
                    .addComponent(tfNumber))
                .addContainerGap())
        );
        optionalFieldsPanelLayout.setVerticalGroup(
            optionalFieldsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(optionalFieldsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(optionalFieldsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfVolume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lVolume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(optionalFieldsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lNumber))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(optionalFieldsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfSeries, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lSeries))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(optionalFieldsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lAddress))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(optionalFieldsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfEdition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lEdition))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(optionalFieldsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lMonth))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(optionalFieldsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lNote))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        optionalFieldsScrollPane.setViewportView(optionalFieldsPanel);

        lEditor.setText("Editor");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(optionalFieldsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lTitle)
                            .addComponent(lPublisher)
                            .addComponent(lYear)
                            .addComponent(lBibtexkey)
                            .addComponent(lEditor))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfTitle)
                            .addComponent(tfPublisher)
                            .addComponent(tfEditor)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tfBibtexkey, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tfYear, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lAuthor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfAuthor, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lTitle)
                    .addComponent(tfTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfPublisher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lPublisher))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lYear)
                    .addComponent(tfAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lAuthor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfEditor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lEditor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfBibtexkey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lBibtexkey))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(optionalFieldsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lAddress;
    private javax.swing.JLabel lAuthor;
    private javax.swing.JLabel lBibtexkey;
    private javax.swing.JLabel lEdition;
    private javax.swing.JLabel lEditor;
    private javax.swing.JLabel lMonth;
    private javax.swing.JLabel lNote;
    private javax.swing.JLabel lNumber;
    private javax.swing.JLabel lPublisher;
    private javax.swing.JLabel lSeries;
    private javax.swing.JLabel lTitle;
    private javax.swing.JLabel lVolume;
    private javax.swing.JLabel lYear;
    private javax.swing.JPanel optionalFieldsPanel;
    private javax.swing.JScrollPane optionalFieldsScrollPane;
    private javax.swing.JTextField tfAddress;
    private javax.swing.JTextField tfAuthor;
    private javax.swing.JTextField tfBibtexkey;
    private javax.swing.JTextField tfEdition;
    private javax.swing.JTextField tfEditor;
    private javax.swing.JTextField tfMonth;
    private javax.swing.JTextField tfNote;
    private javax.swing.JTextField tfNumber;
    private javax.swing.JTextField tfPublisher;
    private javax.swing.JTextField tfSeries;
    private javax.swing.JTextField tfTitle;
    private javax.swing.JTextField tfVolume;
    private javax.swing.JTextField tfYear;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the tfAddress
     */
    public javax.swing.JTextField getTfAddress() {
        return tfAddress;
    }

    /**
     * @param tfAddress the tfAddress to set
     */
    public void setTfAddress(javax.swing.JTextField tfAddress) {
        this.tfAddress = tfAddress;
    }

    /**
     * @return the tfAuthor
     */
    public javax.swing.JTextField getTfAuthor() {
        return tfAuthor;
    }

    /**
     * @param tfAuthor the tfAuthor to set
     */
    public void setTfAuthor(javax.swing.JTextField tfAuthor) {
        this.tfAuthor = tfAuthor;
    }

    /**
     * @return the tfBibtexkey
     */
    public javax.swing.JTextField getTfBibtexkey() {
        return tfBibtexkey;
    }

    /**
     * @param tfBibtexkey the tfBibtexkey to set
     */
    public void setTfBibtexkey(javax.swing.JTextField tfBibtexkey) {
        this.tfBibtexkey = tfBibtexkey;
    }

    /**
     * @return the tfEdition
     */
    public javax.swing.JTextField getTfEdition() {
        return tfEdition;
    }

    /**
     * @param tfEdition the tfEdition to set
     */
    public void setTfEdition(javax.swing.JTextField tfEdition) {
        this.tfEdition = tfEdition;
    }

    /**
     * @return the tfEditor
     */
    public javax.swing.JTextField getTfEditor() {
        return tfEditor;
    }

    /**
     * @param tfEditor the tfEditor to set
     */
    public void setTfEditor(javax.swing.JTextField tfEditor) {
        this.tfEditor = tfEditor;
    }

    /**
     * @return the tfMonth
     */
    public javax.swing.JTextField getTfMonth() {
        return tfMonth;
    }

    /**
     * @param tfMonth the tfMonth to set
     */
    public void setTfMonth(javax.swing.JTextField tfMonth) {
        this.tfMonth = tfMonth;
    }

    /**
     * @return the tfNote
     */
    public javax.swing.JTextField getTfNote() {
        return tfNote;
    }

    /**
     * @param tfNote the tfNote to set
     */
    public void setTfNote(javax.swing.JTextField tfNote) {
        this.tfNote = tfNote;
    }

    /**
     * @return the tfNumber
     */
    public javax.swing.JTextField getTfNumber() {
        return tfNumber;
    }

    /**
     * @param tfNumber the tfNumber to set
     */
    public void setTfNumber(javax.swing.JTextField tfNumber) {
        this.tfNumber = tfNumber;
    }

    /**
     * @return the tfPublisher
     */
    public javax.swing.JTextField getTfPublisher() {
        return tfPublisher;
    }

    /**
     * @param tfPublisher the tfPublisher to set
     */
    public void setTfPublisher(javax.swing.JTextField tfPublisher) {
        this.tfPublisher = tfPublisher;
    }

    /**
     * @return the tfSeries
     */
    public javax.swing.JTextField getTfSeries() {
        return tfSeries;
    }

    /**
     * @param tfSeries the tfSeries to set
     */
    public void setTfSeries(javax.swing.JTextField tfSeries) {
        this.tfSeries = tfSeries;
    }

    /**
     * @return the tfTitle
     */
    public javax.swing.JTextField getTfTitle() {
        return tfTitle;
    }

    /**
     * @param tfTitle the tfTitle to set
     */
    public void setTfTitle(javax.swing.JTextField tfTitle) {
        this.tfTitle = tfTitle;
    }

    /**
     * @return the tfVolume
     */
    public javax.swing.JTextField getTfVolume() {
        return tfVolume;
    }

    /**
     * @param tfVolume the tfVolume to set
     */
    public void setTfVolume(javax.swing.JTextField tfVolume) {
        this.tfVolume = tfVolume;
    }

    /**
     * @return the tfYear
     */
    public javax.swing.JTextField getTfYear() {
        return tfYear;
    }

    /**
     * @param tfYear the tfYear to set
     */
    public void setTfYear(javax.swing.JTextField tfYear) {
        this.tfYear = tfYear;
    }
}
