
package com.myssyt.bibtex.panels;

import javax.swing.JTextField ;
import javax.swing.JPanel;

/**
 *
 * @author jphkylli
 */
public class InproceedingsPanel extends JPanel {
    /*
        An article in a conference proceedings. 
        Required fields: 
            author, title, booktitle, year. 
        Optional fields: 
            editor, volume or number, series, pages, address, month, organization, publisher, note.
    */

    /**
     * Creates new form BookPanel
     */
    public InproceedingsPanel() {
        initComponents();
    }
    
    public void clearTextFields() {
        
        optionalFieldsScrollPane.getVerticalScrollBar().setValue(optionalFieldsScrollPane.getVerticalScrollBar().getMinimum());
        
        getTfBibtexkey().setText("");
        
        getTfAuthor().setText("");
        getTfTitle().setText("");
        getTfBooktitle().setText("");
        getTfYear().setText("");
        
        getTfEditor().setText("");
        getTfVolume().setText("");
        getTfNumber().setText("");
        getTfSeries().setText("");
        getTfPages().setText("");
        getTfAddress().setText("");
        getTfMonth().setText("");
        getTfOrganization().setText("");
        getTfPublisher().setText("");
        getTfNote().setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lAuthor = new javax.swing.JLabel();
        tfAuthor = new javax.swing.JTextField();
        tfTitle = new javax.swing.JTextField();
        lTitle = new javax.swing.JLabel();
        tfBooktitle = new javax.swing.JTextField();
        lBooktitle = new javax.swing.JLabel();
        tfYear = new javax.swing.JTextField();
        lYear = new javax.swing.JLabel();
        tfBibtexkey = new javax.swing.JTextField();
        lBibtexkey = new javax.swing.JLabel();
        optionalFieldsScrollPane = new javax.swing.JScrollPane();
        optionalFieldsPanel = new javax.swing.JPanel();
        lEditor = new javax.swing.JLabel();
        tfEditor = new javax.swing.JTextField();
        tfVolume = new javax.swing.JTextField();
        tfNumber = new javax.swing.JTextField();
        tfSeries = new javax.swing.JTextField();
        tfPages = new javax.swing.JTextField();
        lVolume = new javax.swing.JLabel();
        lNumber = new javax.swing.JLabel();
        lSeries = new javax.swing.JLabel();
        lPages = new javax.swing.JLabel();
        tfAddress = new javax.swing.JTextField();
        tfMonth = new javax.swing.JTextField();
        tfOrganization = new javax.swing.JTextField();
        tfPublisher = new javax.swing.JTextField();
        tfNote = new javax.swing.JTextField();
        lAddress = new javax.swing.JLabel();
        lMonth = new javax.swing.JLabel();
        lOrganization = new javax.swing.JLabel();
        lPublisher = new javax.swing.JLabel();
        lNote = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createTitledBorder("InProceedings"));
        setPreferredSize(new java.awt.Dimension(100, 100));

        lAuthor.setText("Author");

        lTitle.setText("Title");

        lBooktitle.setText("Booktitle");

        lYear.setText("Year");

        lBibtexkey.setText("Bibtexkey");

        optionalFieldsScrollPane.setBorder(javax.swing.BorderFactory.createTitledBorder("Optional Fields"));
        optionalFieldsScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        lEditor.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lEditor.setText("Editor");
        lEditor.setPreferredSize(new java.awt.Dimension(90, 16));

        lVolume.setText("Volume");

        lNumber.setText("Number");

        lSeries.setText("Series");

        lPages.setText("Pages");

        lAddress.setText("Address");

        lMonth.setText("Month");

        lOrganization.setText("Organization");

        lPublisher.setText("Publisher");

        lNote.setText("Note");

        javax.swing.GroupLayout optionalFieldsPanelLayout = new javax.swing.GroupLayout(optionalFieldsPanel);
        optionalFieldsPanel.setLayout(optionalFieldsPanelLayout);
        optionalFieldsPanelLayout.setHorizontalGroup(
            optionalFieldsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(optionalFieldsPanelLayout.createSequentialGroup()
                .addGroup(optionalFieldsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lVolume)
                    .addComponent(lNumber)
                    .addComponent(lSeries)
                    .addComponent(lPages)
                    .addComponent(lAddress)
                    .addComponent(lMonth)
                    .addComponent(lOrganization)
                    .addComponent(lPublisher)
                    .addComponent(lNote)
                    .addComponent(lEditor, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(optionalFieldsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfVolume)
                    .addComponent(tfEditor)
                    .addComponent(tfNumber)
                    .addComponent(tfSeries)
                    .addComponent(tfPages)
                    .addComponent(tfAddress)
                    .addComponent(tfMonth)
                    .addComponent(tfOrganization)
                    .addComponent(tfPublisher)
                    .addComponent(tfNote, javax.swing.GroupLayout.DEFAULT_SIZE, 648, Short.MAX_VALUE))
                .addContainerGap())
        );
        optionalFieldsPanelLayout.setVerticalGroup(
            optionalFieldsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(optionalFieldsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(optionalFieldsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lEditor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfEditor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(optionalFieldsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfVolume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lVolume))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(optionalFieldsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lNumber))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(optionalFieldsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfSeries, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lSeries))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(optionalFieldsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfPages, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lPages))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(optionalFieldsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lAddress))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(optionalFieldsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lMonth))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(optionalFieldsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfOrganization, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lOrganization))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(optionalFieldsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfPublisher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lPublisher))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(optionalFieldsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lNote))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        optionalFieldsScrollPane.setViewportView(optionalFieldsPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(optionalFieldsScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 710, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lAuthor)
                            .addComponent(lTitle)
                            .addComponent(lBooktitle)
                            .addComponent(lYear)
                            .addComponent(lBibtexkey))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfAuthor)
                            .addComponent(tfTitle)
                            .addComponent(tfBooktitle)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(tfBibtexkey, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                                    .addComponent(tfYear, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lAuthor)
                    .addComponent(tfAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lTitle))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfBooktitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lBooktitle))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lYear))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfBibtexkey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lBibtexkey))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(optionalFieldsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lAddress;
    private javax.swing.JLabel lAuthor;
    private javax.swing.JLabel lBibtexkey;
    private javax.swing.JLabel lBooktitle;
    private javax.swing.JLabel lEditor;
    private javax.swing.JLabel lMonth;
    private javax.swing.JLabel lNote;
    private javax.swing.JLabel lNumber;
    private javax.swing.JLabel lOrganization;
    private javax.swing.JLabel lPages;
    private javax.swing.JLabel lPublisher;
    private javax.swing.JLabel lSeries;
    private javax.swing.JLabel lTitle;
    private javax.swing.JLabel lVolume;
    private javax.swing.JLabel lYear;
    private javax.swing.JPanel optionalFieldsPanel;
    private javax.swing.JScrollPane optionalFieldsScrollPane;
    private javax.swing.JTextField tfAddress;
    private javax.swing.JTextField tfAuthor;
    private javax.swing.JTextField tfBibtexkey;
    private javax.swing.JTextField tfBooktitle;
    private javax.swing.JTextField tfEditor;
    private javax.swing.JTextField tfMonth;
    private javax.swing.JTextField tfNote;
    private javax.swing.JTextField tfNumber;
    private javax.swing.JTextField tfOrganization;
    private javax.swing.JTextField tfPages;
    private javax.swing.JTextField tfPublisher;
    private javax.swing.JTextField tfSeries;
    private javax.swing.JTextField tfTitle;
    private javax.swing.JTextField tfVolume;
    private javax.swing.JTextField tfYear;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the tfAddress
     */
    public JTextField getTfAddress() {
        return tfAddress;
    }

    /**
     * @param tfAddress the tfAddress to set
     */
    public void setTfAddress(JTextField tfAddress) {
        this.tfAddress = tfAddress;
    }

    /**
     * @return the tfAuthor
     */
    public JTextField getTfAuthor() {
        return tfAuthor;
    }

    /**
     * @param tfAuthor the tfAuthor to set
     */
    public void setTfAuthor(JTextField tfAuthor) {
        this.tfAuthor = tfAuthor;
    }

    /**
     * @return the tfBibtexkey
     */
    public JTextField getTfBibtexkey() {
        return tfBibtexkey;
    }

    /**
     * @param tfBibtexkey the tfBibtexkey to set
     */
    public void setTfBibtexkey(JTextField tfBibtexkey) {
        this.tfBibtexkey = tfBibtexkey;
    }

    /**
     * @return the tfBooktitle
     */
    public JTextField getTfBooktitle() {
        return tfBooktitle;
    }

    /**
     * @param tfBooktitle the tfBooktitle to set
     */
    public void setTfBooktitle(JTextField tfBooktitle) {
        this.tfBooktitle = tfBooktitle;
    }

    /**
     * @return the tfEditor
     */
    public JTextField getTfEditor() {
        return tfEditor;
    }

    /**
     * @param tfEditor the tfEditor to set
     */
    public void setTfEditor(JTextField tfEditor) {
        this.tfEditor = tfEditor;
    }

    /**
     * @return the tfMonth
     */
    public JTextField getTfMonth() {
        return tfMonth;
    }

    /**
     * @param tfMonth the tfMonth to set
     */
    public void setTfMonth(JTextField tfMonth) {
        this.tfMonth = tfMonth;
    }

    /**
     * @return the tfNote
     */
    public JTextField getTfNote() {
        return tfNote;
    }

    /**
     * @param tfNote the tfNote to set
     */
    public void setTfNote(JTextField tfNote) {
        this.tfNote = tfNote;
    }

    /**
     * @return the tfNumber
     */
    public JTextField getTfNumber() {
        return tfNumber;
    }

    /**
     * @param tfNumber the tfNumber to set
     */
    public void setTfNumber(JTextField tfNumber) {
        this.tfNumber = tfNumber;
    }

    /**
     * @return the tfOrganization
     */
    public JTextField getTfOrganization() {
        return tfOrganization;
    }

    /**
     * @param tfOrganization the tfOrganization to set
     */
    public void setTfOrganization(JTextField tfOrganization) {
        this.tfOrganization = tfOrganization;
    }

    /**
     * @return the tfPages
     */
    public JTextField getTfPages() {
        return tfPages;
    }

    /**
     * @param tfPages the tfPages to set
     */
    public void setTfPages(JTextField tfPages) {
        this.tfPages = tfPages;
    }

    /**
     * @return the tfPublisher
     */
    public JTextField getTfPublisher() {
        return tfPublisher;
    }

    /**
     * @param tfPublisher the tfPublisher to set
     */
    public void setTfPublisher(JTextField tfPublisher) {
        this.tfPublisher = tfPublisher;
    }

    /**
     * @return the tfSeries
     */
    public JTextField getTfSeries() {
        return tfSeries;
    }

    /**
     * @param tfSeries the tfSeries to set
     */
    public void setTfSeries(JTextField tfSeries) {
        this.tfSeries = tfSeries;
    }

    /**
     * @return the tfTitle
     */
    public JTextField getTfTitle() {
        return tfTitle;
    }

    /**
     * @param tfTitle the tfTitle to set
     */
    public void setTfTitle(JTextField tfTitle) {
        this.tfTitle = tfTitle;
    }

    /**
     * @return the tfVolume
     */
    public JTextField getTfVolume() {
        return tfVolume;
    }

    /**
     * @param tfVolume the tfVolume to set
     */
    public void setTfVolume(JTextField tfVolume) {
        this.tfVolume = tfVolume;
    }

    /**
     * @return the tfYear
     */
    public JTextField getTfYear() {
        return tfYear;
    }

    /**
     * @param tfYear the tfYear to set
     */
    public void setTfYear(JTextField tfYear) {
        this.tfYear = tfYear;
    }

    
}
